"""initial load

Revision ID: bfba60c2db69
Revises: 
Create Date: 2025-09-22 13:51:21.574294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfba60c2db69'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_kuenstler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_kuenstler_id'), 't_kuenstler', ['id'], unique=False)
    op.create_table('t_material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bezeichnung', sa.String(), nullable=False),
    sa.Column('spezifikation', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_material_id'), 't_material', ['id'], unique=False)
    op.create_table('t_polymerring',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farbe', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_polymerring_id'), 't_polymerring', ['id'], unique=False)
    op.create_table('t_praegung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('herkunftsbezeichnung', sa.String(), nullable=False),
    sa.Column('standort', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_praegung_id'), 't_praegung', ['id'], unique=False)
    op.create_table('t_serie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bezeichnung', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_serie_id'), 't_serie', ['id'], unique=False)
    op.create_table('t_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('erstellt_am', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_user_id'), 't_user', ['id'], unique=False)
    op.create_table('t_apikey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_apikey_id'), 't_apikey', ['id'], unique=False)
    op.create_table('t_muenze',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titel', sa.String(), nullable=False),
    sa.Column('ausgabedatum', sa.Date(), nullable=False),
    sa.Column('nennwert', sa.Float(), nullable=True),
    sa.Column('praegung_id', sa.Integer(), nullable=False),
    sa.Column('kuenstler_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('polymerring_id', sa.Integer(), nullable=True),
    sa.Column('gewicht', sa.Float(), nullable=False),
    sa.Column('masse', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['kuenstler_id'], ['t_kuenstler.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['t_material.id'], ),
    sa.ForeignKeyConstraint(['polymerring_id'], ['t_polymerring.id'], ),
    sa.ForeignKeyConstraint(['praegung_id'], ['t_praegung.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_muenze_id'), 't_muenze', ['id'], unique=False)
    op.create_table('t_serie_muenze',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serie_id', sa.Integer(), nullable=True),
    sa.Column('muenze_id', sa.Integer(), nullable=True),
    sa.Column('reihenfolge', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['muenze_id'], ['t_muenze.id'], ),
    sa.ForeignKeyConstraint(['serie_id'], ['t_serie.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serie_id', 'muenze_id', name='uq_serie_muenze'),
    sa.UniqueConstraint('serie_id', 'reihenfolge', name='uq_serie_muenze_reihenfolge')
    )
    op.create_index(op.f('ix_t_serie_muenze_id'), 't_serie_muenze', ['id'], unique=False)
    op.create_index(op.f('ix_t_serie_muenze_muenze_id'), 't_serie_muenze', ['muenze_id'], unique=False)
    op.create_index(op.f('ix_t_serie_muenze_serie_id'), 't_serie_muenze', ['serie_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_serie_muenze_serie_id'), table_name='t_serie_muenze')
    op.drop_index(op.f('ix_t_serie_muenze_muenze_id'), table_name='t_serie_muenze')
    op.drop_index(op.f('ix_t_serie_muenze_id'), table_name='t_serie_muenze')
    op.drop_table('t_serie_muenze')
    op.drop_index(op.f('ix_t_muenze_id'), table_name='t_muenze')
    op.drop_table('t_muenze')
    op.drop_index(op.f('ix_t_apikey_id'), table_name='t_apikey')
    op.drop_table('t_apikey')
    op.drop_index(op.f('ix_t_user_id'), table_name='t_user')
    op.drop_table('t_user')
    op.drop_index(op.f('ix_t_serie_id'), table_name='t_serie')
    op.drop_table('t_serie')
    op.drop_index(op.f('ix_t_praegung_id'), table_name='t_praegung')
    op.drop_table('t_praegung')
    op.drop_index(op.f('ix_t_polymerring_id'), table_name='t_polymerring')
    op.drop_table('t_polymerring')
    op.drop_index(op.f('ix_t_material_id'), table_name='t_material')
    op.drop_table('t_material')
    op.drop_index(op.f('ix_t_kuenstler_id'), table_name='t_kuenstler')
    op.drop_table('t_kuenstler')
    # ### end Alembic commands ###
